import {
  Activity,
  Baby,
  Bell,
  BookOpen,
  Calendar,
  Camera,
  Home,
  Moon,
  Ruler,
  Settings,
  Sparkles,
  Stethoscope,
  Syringe,
  Timer,
  Utensils,
  UtensilsCrossed,
} from "lucide-react";

export const NAV_ITEMS = [
  { key: "dashboard", href: "/dashboard", icon: Home },
  { key: "baby", href: "/dashboard/baby", icon: Baby },
  { key: "growth", href: "/dashboard/growth", icon: Ruler },
  { key: "feeding", href: "/dashboard/feeding", icon: Utensils },
  { key: "feedingCalculator", href: "/dashboard/feeding/calculator", icon: Activity },
  { key: "tastings", href: "/dashboard/tastings", icon: UtensilsCrossed },
  { key: "foodCombinations", href: "/dashboard/tastings/combinations", icon: Sparkles },
  { key: "milestones", href: "/dashboard/milestones", icon: Calendar },
  { key: "tummyTime", href: "/dashboard/tummy-time", icon: Timer },
  { key: "sleep", href: "/dashboard/sleep", icon: Moon },
  { key: "vaccinations", href: "/dashboard/vaccinations", icon: Syringe },
  { key: "wellBaby", href: "/dashboard/well-baby", icon: Stethoscope },
  { key: "journal", href: "/dashboard/journal", icon: BookOpen },
  { key: "reminders", href: "/dashboard/reminders", icon: Bell },
  { key: "gallery", href: "/dashboard/gallery", icon: Camera },
  { key: "settings", href: "/dashboard/settings", icon: Settings },
] as const;

export const QUICK_ACTIONS = [
  { key: "feeding", href: "/dashboard/feeding?action=add", icon: Utensils },
  { key: "sleep", href: "/dashboard/sleep?action=add", icon: Moon },
  { key: "growth", href: "/dashboard/growth?action=add", icon: Ruler },
  { key: "tasting", href: "/dashboard/tastings?action=add", icon: UtensilsCrossed },
  { key: "milestone", href: "/dashboard/milestones?action=add", icon: Calendar },
] as const;
